# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0002_auto_20170404_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obisk',
            name='datum',
            field=models.DateTimeField(),
        ),
    ]
