# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obisk', '0004_auto_20170413_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obisk',
            name='datum',
        ),
        migrations.AddField(
            model_name='obisk',
            name='dejanski_datum',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obisk',
            name='delovni_nalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.DelovniNalog'),
        ),
        migrations.AddField(
            model_name='obisk',
            name='je_opravljen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obisk',
            name='nadomestna_patronazna_sestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obisk_nadomestna_patronazna_sestra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obisk',
            name='predvideni_datum',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obisk',
            name='patronazna_sestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obisk_patronazna_sestra', to=settings.AUTH_USER_MODEL),
        ),
    ]
