# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0019_auto_20170420_2131'),
        ('obisk', '0007_auto_20170420_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meritev',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255)),
                ('merska_enota', models.CharField(default=django.db.models.deletion.SET_NULL, max_length=20, null=True)),
                ('sp_meja', models.IntegerField(blank=True, null=True)),
                ('zg_meja', models.IntegerField(blank=True, null=True)),
                ('vrsta_obsika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.VrstaObiska')),
            ],
        ),
        migrations.CreateModel(
            name='MeritveNaObisku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrednost', models.CharField(max_length=1000)),
                ('id_meritve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obisk.Meritev')),
                ('id_obisk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obisk.Obisk')),
            ],
        ),
        migrations.AddField(
            model_name='obisk',
            name='id_meritev',
            field=models.ManyToManyField(blank=True, through='obisk.MeritveNaObisku', to='obisk.Meritev'),
        ),
    ]
