# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0008_auto_20170420_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritev',
            name='merska_enota',
        ),
    ]
