# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0009_remove_meritev_merska_enota'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritev',
            name='merska_enota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
