# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0010_meritev_merska_enota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obisk',
            name='delovni_nalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obisk', to='delovniNalog.DelovniNalog'),
        ),
    ]
