# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0012_auto_20170430_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritev',
            name='enkraten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meritev',
            name='je_obvezen',
            field=models.BooleanField(default=False),
        ),
    ]
