# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0013_auto_20170515_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obisk',
            name='konec_nadomescanja',
        ),
        migrations.RemoveField(
            model_name='obisk',
            name='zacetek_nadomescanja',
        ),
    ]
