# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0013_auto_20170512_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritev',
            name='meritev_novorojencka',
            field=models.BooleanField(default=False),
        ),
    ]
