# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0014_meritev_meritev_novorojencka'),
        ('obisk', '0014_auto_20170515_1134'),
    ]

    operations = [
    ]
