# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0015_merge_20170519_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritev',
            name='tip',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
