# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obisk', '0016_meritev_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='je_prvi',
            field=models.BooleanField(default=False),
        ),
    ]
