# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delavec',
            fields=[
                ('osebna_sifra', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('geslo', models.CharField(max_length=128)),
                ('priimek', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='SifraUstanove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaDelavca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='delavec',
            name='sifra_ustanove',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SifraUstanove'),
        ),
        migrations.AddField(
            model_name='delavec',
            name='vrsta_delavca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.VrstaDelavca'),
        ),
    ]
