# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170323_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktnaOseba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priimek', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('st_kartice', models.IntegerField(primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=255)),
                ('datum_rojstva', models.DateField()),
                ('spol', models.BooleanField()),
                ('kontaktna_oseba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.KontaktnaOseba')),
            ],
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('stevilka', models.IntegerField(primary_key=True, serialize=False)),
                ('kraj', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SifraOkolisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SorodstvenoRazmerje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('priimek', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='delavec',
            name='email',
        ),
        migrations.RemoveField(
            model_name='delavec',
            name='geslo',
        ),
        migrations.RemoveField(
            model_name='delavec',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='delavec',
            name='priimek',
        ),
        migrations.RemoveField(
            model_name='delavec',
            name='tel',
        ),
        migrations.AddField(
            model_name='sifraustanove',
            name='hisna_stevilka',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sifraustanove',
            name='ulica',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sifraustanove',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pacient',
            name='posta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Posta'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='sifra_okolisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SifraOkolisa'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='uporabnik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Uporabnik'),
        ),
        migrations.AddField(
            model_name='kontaktnaoseba',
            name='sorodstveno_razmerje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SorodstvenoRazmerje'),
        ),
        migrations.AddField(
            model_name='delavec',
            name='uporabnik',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Uporabnik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sifraustanove',
            name='posta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Posta'),
        ),
    ]
