# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170324_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='uporabnik',
            name='je_admin',
            field=models.BooleanField(default=False),
        ),
    ]
