# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uporabnik_je_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorodstvenorazmerje',
            name='naziv',
            field=models.CharField(max_length=40),
        ),
    ]
