# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170325_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='je_aktiviran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacient',
            name='vezani_pacienti',
            field=models.ManyToManyField(null=True, related_name='_pacient_vezani_pacienti_+', to='accounts.Pacient'),
        ),
    ]
