# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170328_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='hisna_stevilka',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacient',
            name='kontaktna_oseba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.KontaktnaOseba'),
        ),
    ]
