# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_pacient_hisna_stevilka'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='hisna_stevilka',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
