# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170328_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='hisna_stevilka',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='vezani_pacienti',
            field=models.ManyToManyField(blank=True, related_name='_pacient_vezani_pacienti_+', to='accounts.Pacient'),
        ),
    ]
