# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170404_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontaktnaoseba',
            name='sorodstveno_razmerje',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
