# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170407_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='delavec',
            name='sifra_okolisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SifraOkolisa'),
        ),
    ]
