# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delavec_sifra_okolisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktnaoseba',
            name='hisna_stevilka',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontaktnaoseba',
            name='posta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Posta'),
        ),
        migrations.AddField(
            model_name='kontaktnaoseba',
            name='ulica',
            field=models.CharField(default='Ulica Bratov Tatov', max_length=255),
            preserve_default=False,
        ),
    ]
