# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170412_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='KadrovskaDelavec',
            fields=[
                ('osebna_sifra', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=30)),
                ('priimek', models.CharField(max_length=30)),
            ],
        ),
    ]
