# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170419_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='vezani_pacienti',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.VezaniPacient'),
            preserve_default=False,
        ),
    ]
