# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_pacient_vezani_pacienti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='vezani_pacienti',
        ),
        migrations.AddField(
            model_name='vezanipacient',
            name='pacient_skrbni',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pacient_skrbnik', to='accounts.Pacient'),
            preserve_default=False,
        ),
    ]
