# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_vezanipacient_pacient_skrbni'),
    ]

    operations = [
        migrations.AddField(
            model_name='vezanipacient',
            name='pacient_skrbnik',
            field=models.ForeignKey(default=111222333, on_delete=django.db.models.deletion.CASCADE, related_name='vezani_pacienti', to='accounts.Pacient'),
            preserve_default=False,
        ),
    ]
