# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_kontaktnaoseba_sorodstveno_razmerje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vezanipacient',
            name='sorodstveno_razmerje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SorodstvenoRazmerje'),
        ),
    ]
