# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_vezanipacient_sorodstveno_razmerje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vezanipacient',
            name='sorodstveno_razmerje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SorodstvenoRazmerje'),
        ),
    ]
