# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170515_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delavec',
            name='uporabnik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delavec', to=settings.AUTH_USER_MODEL),
        ),
    ]
