# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obisk', '0001_initial'),
        ('accounts', '0006_auto_20170325_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolezen',
            fields=[
                ('sifra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DelovniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaObiska',
            fields=[
                ('sifra', models.IntegerField(primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zdravilo',
            fields=[
                ('sifra', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='id_materiala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.Material'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='id_obiska',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obisk.Obisk'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='id_pacienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Pacient'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='sifra_bolezni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.Bolezen'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='sifra_vrste_obiska',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.VrstaObiska'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='sifra_zdravila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.Zdravilo'),
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='sifra_zdravnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Delavec'),
        ),
    ]