# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0002_auto_20170328_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delovninalog',
            name='sifra_vrste_obiska',
        ),
        migrations.DeleteModel(
            name='VrstaObiska',
        ),
    ]