# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0003_auto_20170329_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrstaObiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='vrste_obiska',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delovniNalog.VrstaObiska'),
        ),
    ]