# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0005_auto_20170403_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovninalog',
            name='casovni_interval',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delovninalog',
            name='casovno_obdobje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
