# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0009_remove_delovninalog_casovni_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='delovninalog',
            name='casovni_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]