# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0011_auto_20170404_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='delovninalog',
            name='id_materiala',
            field=models.ManyToManyField(blank=True, through='delovniNalog.DelovniNalogMaterial', to='delovniNalog.Material'),
        ),
    ]