# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0012_delovninalog_id_materiala'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrstaobiska',
            name='vezani_pacienti',
            field=models.BooleanField(default=False),
        ),
    ]
