# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0013_vrstaobiska_vezani_pacienti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delovninalog',
            name='id_materiala',
        ),
    ]