# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0015_auto_20170404_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelovniNalogMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('id_delovni_nalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delovniNalog.DelovniNalog')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delovniNalog.Material')),
            ],
        ),
        migrations.AddField(
            model_name='delovninalog',
            name='id_materiala',
            field=models.ManyToManyField(blank=True, through='delovniNalog.DelovniNalogMaterial', to='delovniNalog.Material'),
        ),
    ]
