# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0016_auto_20170404_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delovninalogmaterial',
            old_name='id_material',
            new_name='id_materiala',
        ),
    ]