# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0018_auto_20170409_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delovninalog',
            name='id_obiska',
        ),
        migrations.AlterField(
            model_name='delovninalog',
            name='casovno_obdobje',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delovninalog',
            name='datum_prvega_obiska',
            field=models.DateTimeField(),
        ),
    ]
