# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0019_auto_20170420_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='delovninalog',
            name='datum_izdaje',
            field=models.DateField(default=datetime.date(2017, 4, 28)),
        ),
    ]
