# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0020_delovninalog_datum_izdaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovninalog',
            name='datum_izdaje',
            field=models.DateField(default=datetime.datetime(2017, 4, 28, 13, 9, 9, 724853, tzinfo=utc)),
        ),
    ]
