# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0022_auto_20170502_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovninalog',
            name='datum_izdaje',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 12, 34, 1, 136436, tzinfo=utc)),
        ),
    ]
