# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0027_auto_20170508_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovninalog',
            name='datum_izdaje',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 8, 11, 1, 87624, tzinfo=utc)),
        ),
    ]
