# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delovniNalog', '0028_auto_20170515_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovninalog',
            name='datum_izdaje',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 9, 34, 45, 136558, tzinfo=utc)),
        ),
    ]
